A = frozenset(("Ax", "Ay", "Az"))
G = frozenset(("Gx", "Gy", "Gz"))
AG = frozenset(("Ax", "Ay", "Az", "Gx", "Gy", "Gz"))
PR = frozenset(("Pitch", "Roll"))
PULSE_AG = frozenset(("Ax", "Ay", "Az", "Gx", "Gy"))
